### ISSUE TITLE
hi,I'm sorry ，  an Idiot question ,please!

### ISSUE THREAD

**Issue by wodeyouxishijie** [MyCollab/mycollab#18]
I usually use maven with muti-module,but I can't find the parent pom.xml which have &lt;module&gt; child-module&lt;/module&gt; ,then How can I mvn eclipse all module by one command in this project? 
sorry for idiot question...

**Comment by haiphucnguyen** [comment]
We do not use eclipse for any longer. The reason because the product has many sub-projects and it takes a lot of time to build the whole product in Eclipse. This link is helpful if you use the IntelliJ https://community.mycollab.com/docs/developing-mycollab/setup-mycollab-projects-with-intellij-ide/

We also wrote some guidelines in the site community.mycollab.com. If you still have the problem, please post the question to http://support.mycollab.com
