### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Abraka** [MyCollab/mycollab#35]
No update for nearly a year...whats up?

**Comment by sleslie** [comment]
seems quite possible, certainly the code here and the installation instructions don't match up very well

**Comment by haiphucnguyen** [comment]
This project is likely keeping it as is. The reason because it takes time while we maintain both premium and open source editions with the different architects, the cloud edition is moving to the microservice architect while the community still is maintained as the monolithic application. It takes us much time to maintain this open source edition in every release for installation testing, integration testing etc. besides functional testing for other editions.
